---
- name: Initialize dingo_docker_volumes fact
  ansible.builtin.set_fact:
    dingo_docker_volumes:
      - '{{ dingo_ipc_dir }}:{{ dingo_ipc_container_dir }}'
      - '{{ dingo_db_dir }}:{{ dingo_db_container_dir }}'

- name: Add config to dingo_docker_volumes fact
  ansible.builtin.set_fact:
    dingo_docker_volumes: '{{ dingo_docker_volumes | default([]) + [item] }}'
  loop:
    - '{{ dingo_config_host_file }}:{{ dingo_config_file }}:ro'
  when: dingo_manage_config

- name: Add Dingo configuration to container mounts
  ansible.builtin.set_fact:
    dingo_docker_volumes: '{{ dingo_docker_volumes + [dingo_node_config_file ~ ":" ~ dingo_node_config_container_file ~ ":ro"] }}'
  when: dingo_manage_node_config | bool

- name: Add topology to dingo_docker_volumes fact
  ansible.builtin.set_fact:
    dingo_docker_volumes: '{{ dingo_docker_volumes | default([]) + [item] }}'
  loop:
    - '{{ dingo_topology_host_file }}:{{ dingo_topology_file }}:ro'
  when: dingo_manage_topology

- name: Add keys to dingo_docker_volumes fact
  ansible.builtin.set_fact:
    dingo_docker_volumes: '{{ dingo_docker_volumes | default([]) + [item] }}'
  loop:
    - '{{ dingo_keys_dir }}:{{ dingo_keys_container_dir }}:ro'
  when: dingo_block_producer | bool

- name: Create container
  community.docker.docker_container:
    name: '{{ dingo_docker_container_name }}'
    image: '{{ dingo_docker_image }}'
    restart_policy: unless-stopped
    command: '{{ dingo_command if dingo_command | length > 0 else omit }}'
    restart: >-
      {{ (dingo_manage_node_config | bool and dingo_node_config_result.changed | default(false)) or
         (dingo_manage_topology | bool and cardano_topology.changed | default(false)) }}
    ports: '{{ dingo_docker_base_ports + dingo_docker_extra_ports }}'
    env: '{{ dingo_docker_base_env | combine(dingo_extra_env) }}'
    volumes: '{{ dingo_docker_volumes | list }}'
  vars:
    dingo_docker_base_ports:
      - '{{ dingo_port }}:{{ dingo_container_port }}'
      - '{{ dingo_metrics_port }}:{{ dingo_metrics_container_port }}'
    dingo_docker_base_env:
      CARDANO_BLOCK_PRODUCER: '{{ dingo_block_producer | string }}'
      CARDANO_CONFIG: '{{ dingo_config_file }}'
      CARDANO_DATABASE_PATH: '{{ dingo_db_container_dir }}'
      CARDANO_NETWORK: '{{ dingo_network }}'
      CARDANO_NODE_SOCKET_PATH: '{{ dingo_ipc_container_dir }}/{{ dingo_socket_name }}'
      CARDANO_PORT: '{{ dingo_container_port | string }}'
      CARDANO_SHELLEY_KES_KEY: '{{ dingo_shelley_kes_key }}'
      CARDANO_SHELLEY_OPERATIONAL_CERTIFICATE: '{{ dingo_shelley_opcert }}'
      CARDANO_SHELLEY_VRF_KEY: '{{ dingo_shelley_vrf_key }}'
      CARDANO_SOCKET_PATH: '{{ dingo_ipc_container_dir }}/{{ dingo_socket_name }}'
      CARDANO_TOPOLOGY: '{{ dingo_topology_file }}'
      DINGO_SOCKET_PATH: '{{ dingo_ipc_container_dir }}/{{ dingo_socket_name }}'
      RESTORE_SNAPSHOT: '{{ "true" if dingo_restore_snapshot | bool else "" }}'
      SNAPSHOT_DIGEST: '{{ dingo_snapshot_digest }}'
