---
# Install method
cardano_node_api_install_method: 'docker'

# Cardano Node API version
cardano_node_api_version: '0.8.4'

# Cardano network
cardano_node_api_network: mainnet

# Base host directory for node data
cardano_node_dir: /opt/cardano

# IPC directory for host/container
cardano_node_ipc_dir: '{{ cardano_node_dir }}/ipc'
cardano_node_api_ipc_container_dir: '/node-ipc'

# User/group for file/directory ownership
cardano_node_user: root
cardano_node_group: root

# Docker image
cardano_node_api_docker_image: 'ghcr.io/blinklabs-io/cardano-node-api:{{ cardano_node_api_version }}'

# Docker container name
cardano_node_api_docker_container_name: cardano-node-api

# Port for host/container
cardano_node_api_port: 8080
cardano_node_api_container_port: '{{ cardano_node_api_port }}'
cardano_node_api_grpc_port: 9090
cardano_node_api_grpc_container_port: '{{ cardano_node_api_grpc_port }}'

# Metrics port for host/container
cardano_node_api_metrics_port: 8081
cardano_node_api_metrics_container_port: '{{ cardano_node_api_metrics_port }}'

# SSL certificate and key (optional)
cardano_node_api_tls_cert_file_path: ''
cardano_node_api_tls_cert_file_container_path: '{{ cardano_node_api_tls_cert_file_path }}'
cardano_node_api_tls_key_file_path: ''
cardano_node_api_tls_key_file_container_path: '{{ cardano_node_api_tls_key_file_path }}'
