namespace: blinklabs
name: cardano
version: 0.1.0
readme: README.md
authors:
  - Aurora Gaffney <aurora@blinklabs.io>
  - Chris Gianelloni <wolf31o2@blinklabs.io>
description: Ansible playbooks and roles to install Cardano services of various types
license:
  - Apache-2.0
tags:
  - cardano
  - blinklabs
repository: https://github.com/blinklabs-io/ansible-cardano
