---
# Install method
cdnsd_install_method: 'docker'

# cDNSd version
cdnsd_version: '0.16.0'

# Base host directory for node data
cardano_node_dir: /opt/cardano

# DB directory for host/container
cdnsd_db_dir: '{{ cardano_node_dir }}/cdnsd'
cdnsd_db_container_dir: '/db'

# User/group for file/directory ownership
cardano_node_user: root
cardano_node_group: root

# Docker image
cdnsd_docker_image: 'ghcr.io/blinklabs-io/cdnsd:{{ cdnsd_version }}'

# Docker container name
cdnsd_docker_container_name: cdnsd

# Docker container user
# This should generally match the owner of the DB dir
cdnsd_container_user: '{{ cardano_node_user }}'

# Port for host/container
cdnsd_container_port: 53
cdnsd_port: 20053

# Extra env vars for cdnsd
cdnsd_extra_env: {}
