---
# Install method
cdnsd_install_method: 'docker'

# cDNSd version
cdnsd_version: '0.11.1'

# Base host directory for node data
cardano_node_dir: /opt/cardano

# DB directory for host/container
cdnsd_db_dir: '{{ cardano_node_dir }}/cdnsd'
cdnsd_db_container_dir: '/db'

# User/group for file/directory ownership
cardano_node_user: root
cardano_node_group: root

# Docker image
cdnsd_docker_image: 'ghcr.io/blinklabs-io/cdnsd:{{ cdnsd_version }}'

# Docker container name
cdnsd_docker_container_name: cdnsd

# Port for host/container
cdnsd_container_port: 53
cdnsd_port: 20053

# Cardano network
cdnsd_network: preprod

# Configuration variables
cdnsd_indexer_script_address: "addr_test1vr75xezmpxastymx985l3gamuxrwqdwcfrcnjlygs55aynsqu3edq"
cdnsd_indexer_intercept_slot: "50844079"
cdnsd_indexer_intercept_hash: "81325118471fddb00a20327572b371aee7cce13b846a18500d011b9cefd2a34c"
