---
- name: Initialize adder_docker_volumes fact
  set_fact:
    adder_docker_volumes: '{{ adder_docker_volumes | default([]) + [item] }}'
  loop:
    - '{{ cardano_node_ipc_dir }}:{{ adder_ipc_container_dir }}'

- name: Create container
  community.docker.docker_container:
    name: '{{ adder_docker_container_name }}'
    image: '{{ adder_docker_image }}'
    restart_policy: unless-stopped
    command: "{{ adder_arguments | default([]) }}"
    ports:
      - '{{ adder_port }}:{{ adder_container_port }}'
    env:
      CARDANO_NETWORK: '{{ adder_network }}'
    volumes: '{{ adder_docker_volumes | list }}'
