---
- name: Create container
  docker_container:
    name: '{{ kupo_docker_container_name }}'
    image: '{{ kupo_docker_image }}'
    restart_policy: unless-stopped
    command:
      - kupo --node-socket ${CARDANO_NODE_SOCKET_PATH} --host ${LISTEN_HOST} --port ${LISTEN_PORT}
        --log-level ${LOG_LEVEL} --node-config ${CARDANO_CONFIG} --match '*' --defer-db-indexes
        --prune-utxo --since origin --workdir ${KUPO_DATABASE_PATH}
    ports:
      - '{{ kupo_port }}:{{ kupo_container_port }}'
    env:
      CARDANO_CONFIG: '{{ cardano_node_dir }}/config/{{ kupo_network }}-config.json'
      CARDANO_NODE_SOCKET_PATH: '{{ kupo_ipc_container_dir }}'
      KUPO_DATABASE_PATH: '{{ kupo_db_container_dir }}'
      KUPO_NETWORK: '{{ kupo_network }}'
      LISTEN_HOST: 0.0.0.0
      LISTEN_PORT: '{{ kupo_container_port }}'
      LOG_LEVEL: Info
    volumes:
      - '{{ cardano_node_ipc_dir }}:{{ kupo_ipc_container_dir }}'
      - '{{ kupo_db_dir}}:{{ kupo_db_container_dir }}'
