---
- name: Initialize kupo_docker_volumes fact
  set_fact:
    kupo_docker_volumes: '{{ kupo_docker_volumes | default([]) + [item] }}'
  loop:
    - '{{ cardano_node_ipc_dir }}:{{ kupo_ipc_container_dir }}'
    - '{{ kupo_db_dir }}:{{ kupo_db_container_dir }}'

- name: Add config to kupo_docker_volumes fact
  set_fact:
    kupo_docker_volumes: '{{ kupo_docker_volumes | default([]) + [item] }}'
  loop:
    - '{{ cardano_node_config_dir }}:{{ kupo_config_container_dir }}'

- name: Create container
  docker_container:
    name: '{{ kupo_docker_container_name }}'
    image: '{{ kupo_docker_image }}'
    restart_policy: unless-stopped
    command:
      - --node-socket '{{ kupo_ipc_container_dir }}/{{ cardano_node_socket_name }}'
      - --host 0.0.0.0
      - --port '{{ kupo_container_port | string }}'
      - --log-level Info
      - --node-config '{{ kupo_config_file }}'
      - "{{ kupo_arguments | join(' ') }}"
    ports:
      - '{{ kupo_port }}:{{ kupo_container_port }}'
    volumes: '{{ kupo_docker_volumes | list }}'
