---
- name: Initialize ogmios_docker_volumes fact
  set_fact:
    ogmios_docker_volumes: '{{ ogmios_docker_volumes | default([]) + [item] }}'
  loop:
    - '{{ cardano_node_ipc_dir }}:{{ ogmios_ipc_container_dir }}'

- name: Add config to ogmios_docker_volumes fact
  set_fact:
    ogmios_docker_volumes: '{{ ogmios_docker_volumes | default([]) + [item] }}'
  loop:
    - '{{ cardano_node_config_dir }}:{{ ogmios_config_container_dir }}'

- name: Create container
  docker_container:
    name: '{{ ogmios_docker_container_name }}'
    image: '{{ ogmios_docker_image }}'
    restart_policy: unless-stopped
    command:
      - --node-socket '{{ ogmios_ipc_container_dir }}/{{ cardano_node_socket_name }}'
      - --host 0.0.0.0
      - --port '{{ ogmios_container_port | string }}'
      - --log-level Info
      - --node-config '{{ ogmios_config_file }}'
    ports:
      - '{{ ogmios_port }}:{{ ogmios_container_port }}'
    volumes: '{{ ogmios_docker_volumes | list }}'
