---
# Install method
cardano_node_install_method: 'docker'

# Cardano node version
cardano_node_version: '9.1.1'

# Cardano network
cardano_node_network: mainnet

# Base host directory for node data
cardano_node_dir: /opt/cardano

# Config directory for host/container
cardano_node_config_dir: '{{ cardano_node_dir }}/config'
cardano_node_config_container_dir: '{{ cardano_node_config_dir }}'

# DB directory for host/container
cardano_node_db_dir: '{{ cardano_node_dir }}/data'
cardano_node_db_container_dir: '{{ cardano_node_db_dir }}'

# IPC directory for host/container
cardano_node_ipc_dir: '{{ cardano_node_dir }}/ipc'
cardano_node_ipc_container_dir: '{{ cardano_node_ipc_dir }}'

# Topology directory for host/container
cardano_node_topology_dir: '{{ cardano_node_config_dir }}'
cardano_node_topology_container_dir: '{{ cardano_node_topology_dir }}'

# Block producer keys directory for host/container
cardano_node_keys_dir: '{{ cardano_node_config_dir }}/keys'
cardano_node_keys_container_dir: '{{ cardano_node_keys_dir }}'

# User/group for file/directory ownership
cardano_node_user: root
cardano_node_group: root

# Docker image
cardano_node_docker_image: 'ghcr.io/blinklabs-io/cardano-node:{{ cardano_node_version }}'

# Docker container name
cardano_node_docker_container_name: cardano-node

# Docker cardano-cli wrapper script location
cardano_node_docker_cli_script: /usr/local/bin/cardano-cli

# Port for host/container
cardano_node_container_port: 3001
cardano_node_port: '{{ cardano_node_container_port }}'

# Metrics port for host/container
cardano_node_metrics_container_port: 12798
cardano_node_metrics_port: '{{ cardano_node_metrics_container_port }}'

# Socket file name
cardano_node_socket_name: node.socket

# RTS tuning
cardano_node_rts_flags: '-N2 -A64m -I0 -qg -qb --disable-delayed-os-memory-return'

# Config
cardano_node_manage_config: false # this currently controls mounting only
cardano_node_config_file: '{{ cardano_node_config_container_dir }}/{{ cardano_node_network }}/config.json'

# Topology
cardano_node_manage_topology: false
cardano_node_topology_file: '{{ cardano_node_topology_container_dir }}/{{ cardano_node_network }}/topology.json'
cardano_node_topology_use_ledger_after_slot: 128908821
cardano_node_topology_localroots: []
cardano_node_topology_publicroots: []
# Adjust for non-mainnet deployments
cardano_node_topology_bootstrap_peers:
  - address: 'backbone.cardano.iog.io'
    port: 3001
  - address: 'backbone.mainnet.emurgornd.com'
    port: 3001
  - address: 'backbone.mainnet.cardanofoundation.org'
    port: 3001

# Install chrony
chrony_enabled: true

# Mithril configuration
cardano_node_restore_snapshot: true
cardano_node_snapshot_digest: 'latest'

# Block Producer (also controls mounts for keys)
cardano_node_block_producer: false
cardano_node_shelley_kes_key: '{{ cardano_node_keys_container_dir }}/kes.skey'
cardano_node_shelley_opcert: '{{ cardano_node_keys_container_dir }}/node.cert'
cardano_node_shelley_vrf_key: '{{ cardano_node_keys_container_dir }}/vrf.skey'
