---
- name: Create cardano-cli wrapper for Docker
  ansible.builtin.template:
    src: cardano-cli.sh.j2
    dest: '{{ cardano_node_docker_cli_script }}'
    owner: '{{ cardano_node_user }}'
    group: '{{ cardano_node_group }}'
    mode: '0755'

- name: Initialize docker_volumes fact
  set_fact:
    docker_volumes: '{{ docker_volumes | default([]) + [item] }}'
  loop:
    - '{{ cardano_node_ipc_dir }}:{{ cardano_node_ipc_container_dir }}'
    - '{{ cardano_node_db_dir }}:{{ cardano_node_db_container_dir }}'

- name: Add topology to docker_volumes fact
  set_fact:
    docker_volumes: '{{ docker_volumes | default([]) + [item] }}'
  loop:
    - '{{ cardano_node_topology_file }}:{{ cardano_node_topology_file }}'
  when: cardano_node_manage_topology

- name: Create container
  docker_container:
    name: '{{ cardano_node_docker_container_name }}'
    image: '{{ cardano_node_docker_image }}'
    command:
      - run
    restart_policy: unless-stopped
    ports:
      - '{{ cardano_node_port }}:{{ cardano_node_container_port }}'
      - '{{ cardano_node_metrics_port }}:{{ cardano_node_metrics_container_port }}'
    env:
      CARDANO_CONFIG: '{{ cardano_node_config_file }}'
      CARDANO_DATABASE_PATH: '{{ cardano_node_db_container_dir }}'
      CARDANO_NETWORK: '{{ cardano_node_network }}'
      CARDANO_NODE_SOCKET_PATH: '{{ cardano_node_ipc_container_dir }}/{{ cardano_node_socket_name }}'
      CARDANO_PORT: '{{ cardano_node_port | string }}'
      CARDANO_RTS_OPTS: '{{ cardano_node_rts_flags }}'
      CARDANO_SOCKET_PATH: '{{ cardano_node_ipc_container_dir }}/{{ cardano_node_socket_name }}'
      CARDANO_TOPOLOGY: '{{ cardano_node_topology_file }}'
    volumes: '{{ docker_volumes | list }}'
