---
- name: Check install method
  vars:
    _allowed_install_methods: ['docker']
  ansible.builtin.assert:
    that:
      - go_node_install_method in _allowed_install_methods
    fail_msg: 'The specified install method ({{ go_node_install_method }}) is not one of the allowed values ({{ _allowed_install_methods | join(", ") }})'

- name: Install chrony
  package:
    name: chrony
    state: present
  when: chrony_enabled

- name: Create directories for persistent data
  ansible.builtin.file:
    state: directory
    path: '{{ item }}'
    owner: '{{ go_node_user | string }}'
    group: '{{ go_node_group | string }}'
    mode: '0755'
  loop:
    - '{{ go_node_db_dir }}'
    - '{{ go_node_ipc_dir }}'

- name: Create directories for topology
  ansible.builtin.file:
    state: directory
    path: '{{ item }}'
    owner: '{{ go_node_user | string }}'
    group: '{{ go_node_group | string }}'
    mode: '0755'
  loop:
    - '{{ go_node_topology_dir }}'
  when: go_node_manage_topology

- name: Generate custom topology config
  template:
    dest: '{{ go_node_topology_file }}'
    src: custom-topology.json.j2
    owner: '{{ go_node_user | string }}'
    group: '{{ go_node_group | string }}'
    mode: 0644
  register: cardano_topology
  when: go_node_manage_topology

- name: Include docker-related tasks
  ansible.builtin.include_tasks: docker.yml
  when: go_node_install_method == 'docker'
