---
- name: Initialize snek_docker_volumes fact
  set_fact:
    snek_docker_volumes: '{{ snek_docker_volumes | default([]) + [item] }}'
  loop:
    - '{{ cardano_node_ipc_dir }}:{{ snek_ipc_container_dir }}'

- name: Create container
  docker_container:
    name: '{{ snek_docker_container_name }}'
    image: '{{ snek_docker_image }}'
    restart_policy: unless-stopped
    command: "{{ snek_arguments | default([]) }}"
    ports:
      - '{{ snek_port }}:{{ snek_container_port }}'
    env:
      CARDANO_NETWORK: '{{ snek_network }}'
    volumes: '{{ snek_docker_volumes | list }}'
