---
# Install method
kupo_install_method: 'docker'

# Kupo version
kupo_version: '2.5.1'

# Base host directory for node data
cardano_node_dir: /opt/cardano

# DB directory for host/container
kupo_db_dir: '{{ cardano_node_dir }}/kupo'
kupo_db_container_dir: '/db'

# Config directory for host/container
cardano_node_config_dir: '{{ cardano_node_dir }}/config'
kupo_config_container_dir: '{{ cardano_node_config_dir }}'

# IPC directory for host/container
cardano_node_ipc_dir: '{{ cardano_node_dir }}/ipc'
kupo_ipc_container_dir: '/ipc'

# User/group for file/directory ownership
cardano_node_user: root
cardano_node_group: root

# Docker image
kupo_docker_image: 'cardanosolutions/kupo:v{{ kupo_version }}'

# Docker container name
kupo_docker_container_name: kupo

# Port for host/container
kupo_container_port: 1442
kupo_port: '{{ kupo_container_port }}'

# Cardano network
kupo_network: mainnet

cardano_node_config_file: '{{ cardano_node_config_dir }}/{{ kupo_network }}-config.json'
kupo_config_file: '{{ kupo_config_container_dir }}/{{ kupo_network }}-config.json'
cardano_node_socket_name: node.socket

# Kupo arguments (defaults to everything)
kupo_arguments:
  - --match '*'
  - --defer-db-indexes
  - --since origin
  - --workdir '{{ kupo_db_container_dir }}'
