---
- name: Create container
  docker_container:
    name: '{{ tx_submit_api_docker_container_name }}'
    image: '{{ tx_submit_api_docker_image }}'
    restart_policy: unless-stopped
    ports:
      - '{{ tx_submit_api_port }}:{{ tx_submit_api_container_port }}'
      - '{{ tx_submit_api_metrics_port }}:{{ tx_submit_api_metrics_container_port }}'
    env:
      CARDANO_NETWORK: '{{ tx_submit_api_network }}'
    volumes:
      - '{{ cardano_node_ipc_dir }}:{{ tx_submit_api_ipc_container_dir }}'
