---
# Install method
adder_install_method: 'docker'

# Adder version
adder_version: '0.23.1'

# Base host directory for node data
cardano_node_dir: /opt/cardano

# DB directory for host/container
adder_db_dir: '{{ cardano_node_dir }}/adder'

# Config directory for host/container
cardano_node_config_dir: '{{ cardano_node_dir }}/config'
adder_config_container_dir: '{{ cardano_node_config_dir }}'

# IPC directory for host/container
cardano_node_ipc_dir: '{{ cardano_node_dir }}/ipc'
adder_ipc_container_dir: '/node-ipc'

# User/group for file/directory ownership
cardano_node_user: root
cardano_node_group: root

# Docker image
adder_docker_image: 'ghcr.io/blinklabs-io/adder:{{ adder_version }}'

# Docker container name
adder_docker_container_name: adder

# Port for host/container
adder_container_port: 8080
adder_port: '{{ adder_container_port }}'

# Cardano network
adder_network: mainnet

cardano_node_socket_name: node.socket

# adder arguments (defaults to everything)
adder_arguments:
# Local node
  # - '-v'
  # - '{{ cardano_node_ipc_dir }}:{{ adder_ipc_container_dir }}'
  - '-input-chainsync-network'
  - '{{ adder_network }}'
