---
- name: Check install method
  vars:
    _allowed_install_methods: ['docker']
  ansible.builtin.assert:
    that:
      - dolos_install_method in _allowed_install_methods
    fail_msg: 'The specified install method ({{ dolos_install_method }}) is not one of the allowed values ({{ _allowed_install_methods | join(", ") }})'

# We use the node owner and group
- name: Create directories
  ansible.builtin.file:
    state: directory
    path: '{{ item }}'
    owner: '{{ cardano_node_user | string }}'
    group: '{{ cardano_node_group | string }}'
    mode: '0755'
  loop:
    - '{{ cardano_node_ipc_dir }}'
    - '{{ dolos_db_dir }}'
    - '{{ cardano_node_config_dir }}/dolos'

- name: Generate Dolos config
  template:
    dest: '{{ dolos_etc_dir }}/daemon.toml'
    src: 'daemon.toml.j2'
    owner: '{{ cardano_node_user | string }}'
    group: '{{ cardano_node_group | string }}'
    mode: 0644

- name: Unarchive Dolos snapshot
  ansible.builtin.unarchive:
    src: '{{ dolos_snapshot_url | string }}'
    dest: '{{ dolos_db_dir }}'
    remote_src: yes
    creates: '{{ dolos_db_dir }}/ledger'
  when: dolos_snapshot_enabled

- name: Include docker-related tasks
  ansible.builtin.include_tasks: docker.yml
  when: dolos_install_method == 'docker'
