---
# Install method
ogmios_install_method: 'docker'

# Ogmios version
ogmios_version: '6.11.1'

# Base host directory for node data
cardano_node_dir: /opt/cardano

# Config directory for host/container
cardano_node_config_dir: '{{ cardano_node_dir }}/config'
ogmios_config_container_dir: '{{ cardano_node_config_dir }}'

# IPC directory for host/container
cardano_node_ipc_dir: '{{ cardano_node_dir }}/ipc'
ogmios_ipc_container_dir: '/node-ipc'

# User/group for file/directory ownership
cardano_node_user: root
cardano_node_group: root

# Docker image
ogmios_docker_image: 'cardanosolutions/ogmios:v{{ ogmios_version }}'

# Docker container name
ogmios_docker_container_name: ogmios

# Port for host/container
ogmios_container_port: 1337
ogmios_port: '{{ ogmios_container_port }}'

cardano_node_config_file: '{{ cardano_node_config_dir }}/{{ ogmios_network }}/config.json'
ogmios_config_file: '{{ ogmios_config_container_dir }}/{{ ogmios_network }}/config.json'
cardano_node_socket_name: node.socket

# Cardano network
ogmios_network: mainnet
