---
name: Ansible Tests

on:
  pull_request:

jobs:
  build:
    name: Ansible Tests
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Perform sanity testing with ansible-test
        uses: ansible-community/ansible-test-gh-action@b416b6ecf7ddb0ea3b0a51c1d198d715eba52c9d # v1.16.0 https://github.com/ansible-community/ansible-test-gh-action/releases/tag/v1.16.0
        with:
          ansible-core-version: stable-2.13
          testing-type: sanity

      # TODO: uncomment when we have integration tests
      #- name: Perform integration testing with ansible-test
      #  uses: ansible-community/ansible-test-gh-action@release/v1
      #  with:
      #    ansible-core-version: stable-2.13
      #    pre-test-cmd: echo This runs before the ansible-test invocation
      #    python-version: 3.9
      #    target-python-version: 3.9
      #    testing-type: integration
      #    #test-deps: ansible.netcommon

      # TODO: uncomment when we have unit tests
      #- name: Perform unit testing with ansible-test
      #  uses: ansible-community/ansible-test-gh-action@release/v1
      #  with:
      #    ansible-core-version: stable-2.13
      #    pre-test-cmd: echo This runs before the ansible-test invocation
      #    python-version: 3.9
      #    target-python-version: 3.9
      #    testing-type: units
      #    #test-deps: >-
      #    #  ansible.netcommon
      #    #  ansible.utils
